### ISSUE TITLE
stm32f4xx.h missing or not needed? please help

### ISSUE THREAD

**Issue by rusefi** [fetisov/emfat#1]
I love this library and I would love to use it in my project. My first step is to compile the example app.c with make instead of the MDK project.

I've started writing the Makefile and it's failing with 
   ../usb-files/usb_conf.h:34:23: fatal error: stm32f4xx.h: No such file or directory

I am confused. usb-files/usb_conf.h does mention stm32f4xx.h but I believe there is no stm32f4xx.h in the repository? I see you std-periph folder so I was assuming the project is totally self-contained?

Please help.

**Comment by fetisov** [comment]
Please, check next definations in project settings:
-DUSE_STDPERIPH_DRIVER
-DSTM32F4XX
