### ISSUE TITLE
Write posibility?

### ISSUE THREAD

**Issue by biovoid** [fetisov/emfat#3]
Hi,

Is there a chance to handle file writing? Sometimes it can be helpful to update firmware etc

**Comment by fetisov** [comment]
Здравствуйте, Сергей.
К сожалению, качественного решения нет.
emfat, позволяет, например, отслеживать перезапись существующего файла. Данное свойство я использовал для перешивки. Но это работает до тех пор пока драйвер хоста использует последовательное размещение кластеров. Сделать как-то иначе в теории он может.
Другой подход - контролировать изменение файловой таблицы синхронно с записью, которую проводит хост. Это должно работать устойчиво на большинстве платформ, но есть масса способов как "уронить" устройство. Например, начать копирование нескольких файлов или дифрагментацию...
